// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIYsqfQPPWXXhJDuJLMkAUhmKwThwYogY',
    appId: '1:1055050346137:android:804b3577c7d15304599208',
    messagingSenderId: '1055050346137',
    projectId: 'mealroulette-e3f4d',
    storageBucket: 'mealroulette-e3f4d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDIFtuLRd9ZcRX_MWR-PpxvN9HKOUWG6g',
    appId: '1:1055050346137:ios:14bd5b9d56d0af3b599208',
    messagingSenderId: '1055050346137',
    projectId: 'mealroulette-e3f4d',
    storageBucket: 'mealroulette-e3f4d.firebasestorage.app',
    iosBundleId: 'com.sgm17.mealroulette.mealRoulette',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDIFtuLRd9ZcRX_MWR-PpxvN9HKOUWG6g',
    appId: '1:1055050346137:ios:14bd5b9d56d0af3b599208',
    messagingSenderId: '1055050346137',
    projectId: 'mealroulette-e3f4d',
    storageBucket: 'mealroulette-e3f4d.firebasestorage.app',
    iosBundleId: 'com.sgm17.mealroulette.mealRoulette',
  );

}